server:
  port: 8088
spring:
  application:
    name: springboot-rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
  # 生产者组名， 规定在一个应用里面必须是唯一的
    group: ${spring.application.name}
    # 消息发送的超时时间， 毫秒， 默认3s
    send-message-timeout: 3000
    # 消息达到 4096 字节的时候，消息会被压缩。默认就是4096，有利于网络传输，提高性能
    compress-message-body-threshold: 4096
    # 最大的消息限制，默认为128k
    max-message-size: 4194304
    # 同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    # 在内部发送失败时是否重试其他代理。 源码：setRetryAnotherBrokerWhenNotStoreOK，就是指：发送到broker-a失败是否发送到broker-b。这个参数在有多个broker才生效。
    retry-next-server: true
    # 异步 消息发送失败重试次数
    retry-times-when-send-async-failed: 3

