spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/shiro?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: '!QAZ1qaz'
    dbcp2:
      initial-size: 1
      min-idle: 1
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
    password:
  mvc:
    favicon:
      enabled: false
mybatis:
  type-aliases-package: com.zhoufu.springbootshiromybatis.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.zhoufu.springbootshiromybatis.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count\=countSql




