server:
  port: 9000
#spring:
#  jackson:
#    time-zone: GTM+8
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/ngAccount?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8
#    username: root
#    password: '!QAZ1qaz'


#
#scheduled:
#  demo: 0 0 0/1 * * ?