server:
  port: 8080
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url:  jdbc:mysql://127.0.0.1:3306/zf?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
#    username: root
#    password: '!QAZ1qaz'
#mybatis:
#  type-aliases-package: com.zhoufu.springbootshiro.pojo
#  mapper-locations: classpath:mapper/*.xml
